<?php

use Illuminate\Database\Seeder;

class Users95319TableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users_95319')->delete();
        
        \DB::table('users_95319')->insert(array (
            0 => 
            array (
                'firstname' => 'Erick',
                'lastname' => 'Njiru',
                'email' => 'ericknjiru@gmail.com',
                'password' => '$2y$10$J1DqpDzo2a4lQLJLCC4QfOeQ.mvis/4SOASBkR8GJK/mtPyRtyvKu',
                'tel' => '0718931359',
                'age' => 21,
                'type' => 'normal',
                'remember_token' => NULL,
                'created_at' => '2018-07-07 10:47:53',
                'updated_at' => '2018-07-07 10:47:53',
                'gender' => 'Male',
            ),
            1 => 
            array (
                'firstname' => 'Anatola',
                'lastname' => 'Bance',
                'email' => 'abance0@bravesites.com',
                'password' => '2IXn34tvG',
                'tel' => '+7 678 375 1357',
                'age' => 33,
                'type' => 'manager',
                'remember_token' => NULL,
                'created_at' => '2017-10-07 00:00:00',
                'updated_at' => '2018-01-31 00:00:00',
                'gender' => 'Female',
            ),
            2 => 
            array (
                'firstname' => 'Hadria',
                'lastname' => 'Dufaire',
                'email' => 'hdufaire1@php.net',
                'password' => 'OPm6PZcU',
                'tel' => '+86 130 333 6029',
                'age' => 31,
                'type' => 'coach',
                'remember_token' => NULL,
                'created_at' => '2018-05-08 00:00:00',
                'updated_at' => '2017-10-09 00:00:00',
                'gender' => 'Male',
            ),
            3 => 
            array (
                'firstname' => 'Silvia',
                'lastname' => 'Suggett',
                'email' => 'ssuggett2@printfriendly.com',
                'password' => 'cMhuHtG',
                'tel' => '+55 106 359 2918',
                'age' => 27,
                'type' => 'coach',
                'remember_token' => NULL,
                'created_at' => '2017-07-17 00:00:00',
                'updated_at' => '2018-06-16 00:00:00',
                'gender' => 'Male',
            ),
            4 => 
            array (
                'firstname' => 'Deanna',
                'lastname' => 'Linebarger',
                'email' => 'dlinebarger3@scribd.com',
                'password' => '1ffYL3cvh',
                'tel' => '+51 410 973 7188',
                'age' => 51,
                'type' => 'normal',
                'remember_token' => NULL,
                'created_at' => '2017-11-26 00:00:00',
                'updated_at' => '2017-07-17 00:00:00',
                'gender' => 'Female',
            ),
            5 => 
            array (
                'firstname' => 'Devy',
                'lastname' => 'Crissil',
                'email' => 'dcrissil4@phpbb.com',
                'password' => '0HCafpHIz2F',
                'tel' => '+52 511 630 3639',
                'age' => 23,
                'type' => 'normal',
                'remember_token' => NULL,
                'created_at' => '2017-07-10 00:00:00',
                'updated_at' => '2018-05-13 00:00:00',
                'gender' => 'Female',
            ),
            6 => 
            array (
                'firstname' => 'Augustine',
                'lastname' => 'Orbine',
                'email' => 'aorbine5@berkeley.edu',
                'password' => 'krF0vZPf1dL',
                'tel' => '+30 202 708 6875',
                'age' => 50,
                'type' => 'coach',
                'remember_token' => NULL,
                'created_at' => '2018-05-11 00:00:00',
                'updated_at' => '2017-11-11 00:00:00',
                'gender' => 'Male',
            ),
            7 => 
            array (
                'firstname' => 'Randie',
                'lastname' => 'Suston',
                'email' => 'rsuston6@fastcompany.com',
                'password' => 'lPObl43LiXr',
                'tel' => '+1 941 715 3666',
                'age' => 43,
                'type' => 'manager',
                'remember_token' => NULL,
                'created_at' => '2018-02-06 00:00:00',
                'updated_at' => '2018-06-15 00:00:00',
                'gender' => 'Male',
            ),
            8 => 
            array (
                'firstname' => 'Romain',
                'lastname' => 'Cammis',
                'email' => 'rcammis7@infoseek.co.jp',
                'password' => 'ML8V0bFcZUH',
                'tel' => '+420 227 920 5902',
                'age' => 44,
                'type' => 'normal',
                'remember_token' => NULL,
                'created_at' => '2017-12-03 00:00:00',
                'updated_at' => '2017-07-29 00:00:00',
                'gender' => 'Male',
            ),
            9 => 
            array (
                'firstname' => 'Jacenta',
                'lastname' => 'Rookes',
                'email' => 'jrookes8@geocities.jp',
                'password' => '8HEwzrgDf75',
                'tel' => '+1 126 338 0049',
                'age' => 52,
                'type' => 'normal',
                'remember_token' => NULL,
                'created_at' => '2018-03-22 00:00:00',
                'updated_at' => '2018-06-14 00:00:00',
                'gender' => 'Male',
            ),
            10 => 
            array (
                'firstname' => 'Hollie',
                'lastname' => 'Antill',
                'email' => 'hantill9@elpais.com',
                'password' => 'FYmQLdr',
                'tel' => '+996 415 168 2692',
                'age' => 22,
                'type' => 'coach',
                'remember_token' => NULL,
                'created_at' => '2017-10-21 00:00:00',
                'updated_at' => '2018-06-26 00:00:00',
                'gender' => 'Female',
            ),
            11 => 
            array (
                'firstname' => 'Junette',
                'lastname' => 'Dradey',
                'email' => 'jdradeya@jalbum.net',
                'password' => 'LpWj6c1yel1J',
                'tel' => '+86 791 707 7130',
                'age' => 51,
                'type' => 'manager',
                'remember_token' => NULL,
                'created_at' => '2017-08-13 00:00:00',
                'updated_at' => '2017-07-11 00:00:00',
                'gender' => 'Male',
            ),
            12 => 
            array (
                'firstname' => 'Jeno',
                'lastname' => 'Yearnes',
                'email' => 'jyearnesb@godaddy.com',
                'password' => 'BsFZX6WMI',
                'tel' => '+62 725 776 8422',
                'age' => 26,
                'type' => 'manager',
                'remember_token' => NULL,
                'created_at' => '2018-04-02 00:00:00',
                'updated_at' => '2017-09-28 00:00:00',
                'gender' => 'Female',
            ),
            13 => 
            array (
                'firstname' => 'Vassili',
                'lastname' => 'Hrishanok',
                'email' => 'vhrishanokc@paypal.com',
                'password' => 'JM8NtC',
                'tel' => '+593 629 505 7605',
                'age' => 27,
                'type' => 'coach',
                'remember_token' => NULL,
                'created_at' => '2017-12-12 00:00:00',
                'updated_at' => '2018-06-11 00:00:00',
                'gender' => 'Male',
            ),
            14 => 
            array (
                'firstname' => 'Julina',
                'lastname' => 'Matthessen',
                'email' => 'jmatthessend@accuweather.com',
                'password' => 'L0W2uHG',
                'tel' => '+7 430 837 6488',
                'age' => 33,
                'type' => 'normal',
                'remember_token' => NULL,
                'created_at' => '2017-07-31 00:00:00',
                'updated_at' => '2017-08-07 00:00:00',
                'gender' => 'Male',
            ),
            15 => 
            array (
                'firstname' => 'Hale',
                'lastname' => 'Faulkener',
                'email' => 'hfaulkenere@naver.com',
                'password' => 'fpT4i81Ayl',
                'tel' => '+7 720 149 8861',
                'age' => 41,
                'type' => 'normal',
                'remember_token' => NULL,
                'created_at' => '2018-01-31 00:00:00',
                'updated_at' => '2017-12-30 00:00:00',
                'gender' => 'Female',
            ),
            16 => 
            array (
                'firstname' => 'Leicester',
                'lastname' => 'Fieldgate',
                'email' => 'lfieldgatef@slashdot.org',
                'password' => '5m1I5H3qSLO',
                'tel' => '+98 203 480 8273',
                'age' => 20,
                'type' => 'normal',
                'remember_token' => NULL,
                'created_at' => '2017-09-10 00:00:00',
                'updated_at' => '2018-06-19 00:00:00',
                'gender' => 'Male',
            ),
            17 => 
            array (
                'firstname' => 'Rog',
                'lastname' => 'Dunstone',
                'email' => 'rdunstoneg@weebly.com',
                'password' => 'ffPqFrm5aV',
                'tel' => '+86 346 837 8312',
                'age' => 21,
                'type' => 'normal',
                'remember_token' => NULL,
                'created_at' => '2018-05-29 00:00:00',
                'updated_at' => '2018-01-09 00:00:00',
                'gender' => 'Male',
            ),
            18 => 
            array (
                'firstname' => 'Hank',
                'lastname' => 'Cleator',
                'email' => 'hcleatorh@cloudflare.com',
                'password' => 'GRgcbZZ',
                'tel' => '+86 324 446 1247',
                'age' => 32,
                'type' => 'normal',
                'remember_token' => NULL,
                'created_at' => '2018-06-07 00:00:00',
                'updated_at' => '2017-10-12 00:00:00',
                'gender' => 'Male',
            ),
            19 => 
            array (
                'firstname' => 'Ashley',
                'lastname' => 'Stowers',
                'email' => 'astowersi@digg.com',
                'password' => 'c3Vc62yYJIp',
                'tel' => '+977 824 865 2275',
                'age' => 20,
                'type' => 'normal',
                'remember_token' => NULL,
                'created_at' => '2018-06-16 00:00:00',
                'updated_at' => '2018-05-31 00:00:00',
                'gender' => 'Female',
            ),
            20 => 
            array (
                'firstname' => 'Bobbi',
                'lastname' => 'Smorthit',
                'email' => 'bsmorthitj@yelp.com',
                'password' => 'PCjQzGnZ59',
                'tel' => '+86 229 968 2844',
                'age' => 31,
                'type' => 'coach',
                'remember_token' => NULL,
                'created_at' => '2018-02-12 00:00:00',
                'updated_at' => '2017-08-23 00:00:00',
                'gender' => 'Male',
            ),
            21 => 
            array (
                'firstname' => 'Gene',
                'lastname' => 'Beach',
                'email' => 'gbeachk@wordpress.org',
                'password' => 'EJa7fw',
                'tel' => '+62 827 115 8222',
                'age' => 31,
                'type' => 'manager',
                'remember_token' => NULL,
                'created_at' => '2018-01-18 00:00:00',
                'updated_at' => '2017-08-24 00:00:00',
                'gender' => 'Male',
            ),
            22 => 
            array (
                'firstname' => 'Valeda',
                'lastname' => 'Nibley',
                'email' => 'vnibleyl@economist.com',
                'password' => '74APG3usU4TU',
                'tel' => '+45 922 159 3451',
                'age' => 54,
                'type' => 'coach',
                'remember_token' => NULL,
                'created_at' => '2018-03-18 00:00:00',
                'updated_at' => '2018-04-14 00:00:00',
                'gender' => 'Female',
            ),
            23 => 
            array (
                'firstname' => 'Laurie',
                'lastname' => 'Mettrick',
                'email' => 'lmettrickm@arstechnica.com',
                'password' => '9bs7TSCEm',
                'tel' => '+7 819 456 0730',
                'age' => 59,
                'type' => 'coach',
                'remember_token' => NULL,
                'created_at' => '2017-09-20 00:00:00',
                'updated_at' => '2017-12-08 00:00:00',
                'gender' => 'Male',
            ),
            24 => 
            array (
                'firstname' => 'Gardener',
                'lastname' => 'Bellard',
                'email' => 'gbellardn@jigsy.com',
                'password' => 'drLQ6bMTsta',
                'tel' => '+86 570 139 9049',
                'age' => 55,
                'type' => 'coach',
                'remember_token' => NULL,
                'created_at' => '2018-05-13 00:00:00',
                'updated_at' => '2018-04-14 00:00:00',
                'gender' => 'Male',
            ),
            25 => 
            array (
                'firstname' => 'Aguste',
                'lastname' => 'Konig',
                'email' => 'akonigo@flavors.me',
                'password' => 'eeATimUAnfU',
                'tel' => '+48 815 524 8506',
                'age' => 58,
                'type' => 'normal',
                'remember_token' => NULL,
                'created_at' => '2018-04-17 00:00:00',
                'updated_at' => '2018-06-24 00:00:00',
                'gender' => 'Male',
            ),
            26 => 
            array (
                'firstname' => 'Rheta',
                'lastname' => 'Fazzioli',
                'email' => 'rfazziolip@livejournal.com',
                'password' => 'r7eO4iyBck',
                'tel' => '+86 861 700 8040',
                'age' => 34,
                'type' => 'normal',
                'remember_token' => NULL,
                'created_at' => '2018-01-09 00:00:00',
                'updated_at' => '2018-05-04 00:00:00',
                'gender' => 'Male',
            ),
            27 => 
            array (
                'firstname' => 'Johan',
                'lastname' => 'Noorwood',
                'email' => 'jnoorwoodq@ebay.com',
                'password' => 'I52JnkuQea',
                'tel' => '+86 306 843 3452',
                'age' => 51,
                'type' => 'manager',
                'remember_token' => NULL,
                'created_at' => '2017-12-08 00:00:00',
                'updated_at' => '2018-02-11 00:00:00',
                'gender' => 'Female',
            ),
            28 => 
            array (
                'firstname' => 'Milo',
                'lastname' => 'McKibben',
                'email' => 'mmckibbenr@google.it',
                'password' => 'CACMkQAcOhPt',
                'tel' => '+998 748 555 2239',
                'age' => 18,
                'type' => 'normal',
                'remember_token' => NULL,
                'created_at' => '2017-10-12 00:00:00',
                'updated_at' => '2017-10-27 00:00:00',
                'gender' => 'Female',
            ),
            29 => 
            array (
                'firstname' => 'Kit',
                'lastname' => 'Meiner',
                'email' => 'kmeiners@cdbaby.com',
                'password' => 'j8HaYr8jOw',
                'tel' => '+30 472 439 7656',
                'age' => 22,
                'type' => 'manager',
                'remember_token' => NULL,
                'created_at' => '2017-08-18 00:00:00',
                'updated_at' => '2017-08-02 00:00:00',
                'gender' => 'Female',
            ),
            30 => 
            array (
                'firstname' => 'Ethelin',
                'lastname' => 'Findlater',
                'email' => 'efindlatert@hibu.com',
                'password' => 'lERtsXzzLrrW',
                'tel' => '+82 464 221 5829',
                'age' => 58,
                'type' => 'manager',
                'remember_token' => NULL,
                'created_at' => '2017-08-07 00:00:00',
                'updated_at' => '2017-12-23 00:00:00',
                'gender' => 'Male',
            ),
            31 => 
            array (
                'firstname' => 'Ericka',
                'lastname' => 'Jest',
                'email' => 'ejestu@illinois.edu',
                'password' => 'YKkA64uI',
                'tel' => '+46 929 374 5305',
                'age' => 23,
                'type' => 'normal',
                'remember_token' => NULL,
                'created_at' => '2017-07-18 00:00:00',
                'updated_at' => '2018-07-05 00:00:00',
                'gender' => 'Female',
            ),
            32 => 
            array (
                'firstname' => 'Katha',
                'lastname' => 'Lillow',
                'email' => 'klillowv@wufoo.com',
                'password' => 'dc5XphOQ6hjO',
                'tel' => '+98 820 782 7913',
                'age' => 35,
                'type' => 'normal',
                'remember_token' => NULL,
                'created_at' => '2018-01-20 00:00:00',
                'updated_at' => '2017-11-27 00:00:00',
                'gender' => 'Female',
            ),
            33 => 
            array (
                'firstname' => 'Tim',
                'lastname' => 'Battell',
                'email' => 'tbattellw@npr.org',
                'password' => '9BdcL7WX',
                'tel' => '+62 693 221 0580',
                'age' => 50,
                'type' => 'manager',
                'remember_token' => NULL,
                'created_at' => '2018-06-05 00:00:00',
                'updated_at' => '2018-02-03 00:00:00',
                'gender' => 'Male',
            ),
            34 => 
            array (
                'firstname' => 'Konstanze',
                'lastname' => 'Stonestreet',
                'email' => 'kstonestreetx@springer.com',
                'password' => '7P9kOoOm',
                'tel' => '+86 646 518 4064',
                'age' => 44,
                'type' => 'coach',
                'remember_token' => NULL,
                'created_at' => '2018-01-11 00:00:00',
                'updated_at' => '2018-04-14 00:00:00',
                'gender' => 'Male',
            ),
            35 => 
            array (
                'firstname' => 'Amalee',
                'lastname' => 'Kalewe',
                'email' => 'akalewey@twitpic.com',
                'password' => 'YE1AnihkD',
                'tel' => '+970 705 116 6036',
                'age' => 47,
                'type' => 'manager',
                'remember_token' => NULL,
                'created_at' => '2018-01-25 00:00:00',
                'updated_at' => '2017-12-06 00:00:00',
                'gender' => 'Female',
            ),
            36 => 
            array (
                'firstname' => 'Diana',
                'lastname' => 'Loren',
                'email' => 'dlorenz@163.com',
                'password' => 'xqMhlpdiVN',
                'tel' => '+7 554 590 1126',
                'age' => 24,
                'type' => 'normal',
                'remember_token' => NULL,
                'created_at' => '2018-05-24 00:00:00',
                'updated_at' => '2017-12-21 00:00:00',
                'gender' => 'Female',
            ),
            37 => 
            array (
                'firstname' => 'Stephi',
                'lastname' => 'Alliban',
                'email' => 'salliban10@hao123.com',
                'password' => 'mISWlnM',
                'tel' => '+27 707 371 7690',
                'age' => 59,
                'type' => 'manager',
                'remember_token' => NULL,
                'created_at' => '2017-09-14 00:00:00',
                'updated_at' => '2018-01-26 00:00:00',
                'gender' => 'Female',
            ),
            38 => 
            array (
                'firstname' => 'Ginevra',
                'lastname' => 'Bakewell',
                'email' => 'gbakewell11@independent.co.uk',
                'password' => 'VSFFhjLwOFa0',
                'tel' => '+1 828 413 8248',
                'age' => 49,
                'type' => 'coach',
                'remember_token' => NULL,
                'created_at' => '2017-07-29 00:00:00',
                'updated_at' => '2017-09-12 00:00:00',
                'gender' => 'Female',
            ),
            39 => 
            array (
                'firstname' => 'Danyelle',
                'lastname' => 'Pfleger',
                'email' => 'dpfleger12@abc.net.au',
                'password' => 'RkGbsLBV',
                'tel' => '+62 880 698 1054',
                'age' => 41,
                'type' => 'manager',
                'remember_token' => NULL,
                'created_at' => '2018-01-23 00:00:00',
                'updated_at' => '2017-12-08 00:00:00',
                'gender' => 'Male',
            ),
            40 => 
            array (
                'firstname' => 'Redd',
                'lastname' => 'Longbothom',
                'email' => 'rlongbothom13@seattletimes.com',
                'password' => 'IPyo5L',
                'tel' => '+86 914 119 7065',
                'age' => 21,
                'type' => 'coach',
                'remember_token' => NULL,
                'created_at' => '2017-09-09 00:00:00',
                'updated_at' => '2017-07-25 00:00:00',
                'gender' => 'Male',
            ),
            41 => 
            array (
                'firstname' => 'Ortensia',
                'lastname' => 'Couvet',
                'email' => 'ocouvet14@wordpress.com',
                'password' => 'p1dSDJa',
                'tel' => '+62 250 900 9225',
                'age' => 51,
                'type' => 'normal',
                'remember_token' => NULL,
                'created_at' => '2017-11-15 00:00:00',
                'updated_at' => '2017-11-29 00:00:00',
                'gender' => 'Male',
            ),
            42 => 
            array (
                'firstname' => 'Carlene',
                'lastname' => 'Woolward',
                'email' => 'cwoolward15@drupal.org',
                'password' => 'KldSziZP1u',
                'tel' => '+374 796 238 9018',
                'age' => 46,
                'type' => 'coach',
                'remember_token' => NULL,
                'created_at' => '2017-09-17 00:00:00',
                'updated_at' => '2018-02-20 00:00:00',
                'gender' => 'Male',
            ),
            43 => 
            array (
                'firstname' => 'Tish',
                'lastname' => 'Adamiak',
                'email' => 'tadamiak16@unicef.org',
                'password' => 'bKq6l23',
                'tel' => '+86 153 870 4730',
                'age' => 26,
                'type' => 'coach',
                'remember_token' => NULL,
                'created_at' => '2017-11-14 00:00:00',
                'updated_at' => '2017-07-12 00:00:00',
                'gender' => 'Female',
            ),
            44 => 
            array (
                'firstname' => 'Felita',
                'lastname' => 'Andre',
                'email' => 'fandre17@typepad.com',
                'password' => 'mTQa3qIhtpB',
                'tel' => '+86 659 399 8283',
                'age' => 27,
                'type' => 'coach',
                'remember_token' => NULL,
                'created_at' => '2017-11-09 00:00:00',
                'updated_at' => '2018-04-27 00:00:00',
                'gender' => 'Male',
            ),
            45 => 
            array (
                'firstname' => 'Hanni',
                'lastname' => 'Mariault',
                'email' => 'hmariault18@house.gov',
                'password' => 'ltbo0PqlPL3a',
                'tel' => '+52 513 996 5086',
                'age' => 58,
                'type' => 'manager',
                'remember_token' => NULL,
                'created_at' => '2018-04-27 00:00:00',
                'updated_at' => '2018-03-12 00:00:00',
                'gender' => 'Male',
            ),
            46 => 
            array (
                'firstname' => 'Wilmar',
                'lastname' => 'Backe',
                'email' => 'wbacke19@yahoo.co.jp',
                'password' => '8fESlKr',
                'tel' => '+86 465 836 5075',
                'age' => 22,
                'type' => 'coach',
                'remember_token' => NULL,
                'created_at' => '2017-09-17 00:00:00',
                'updated_at' => '2018-04-13 00:00:00',
                'gender' => 'Female',
            ),
            47 => 
            array (
                'firstname' => 'Ruggiero',
                'lastname' => 'Cossum',
                'email' => 'rcossum1a@nifty.com',
                'password' => 'X2Vj4hj8I',
                'tel' => '+56 889 879 3119',
                'age' => 22,
                'type' => 'coach',
                'remember_token' => NULL,
                'created_at' => '2017-12-25 00:00:00',
                'updated_at' => '2018-03-26 00:00:00',
                'gender' => 'Female',
            ),
            48 => 
            array (
                'firstname' => 'Lorianne',
                'lastname' => 'McCray',
                'email' => 'lmccray1b@chronoengine.com',
                'password' => 'LYZCyLHy72GL',
                'tel' => '+86 410 740 6499',
                'age' => 24,
                'type' => 'coach',
                'remember_token' => NULL,
                'created_at' => '2018-06-01 00:00:00',
                'updated_at' => '2017-11-30 00:00:00',
                'gender' => 'Female',
            ),
            49 => 
            array (
                'firstname' => 'Dionisio',
                'lastname' => 'Sebrook',
                'email' => 'dsebrook1c@bloglines.com',
                'password' => 'LAp6MGYA',
                'tel' => '+54 892 679 9520',
                'age' => 52,
                'type' => 'normal',
                'remember_token' => NULL,
                'created_at' => '2017-08-11 00:00:00',
                'updated_at' => '2018-04-27 00:00:00',
                'gender' => 'Male',
            ),
            50 => 
            array (
                'firstname' => 'Deb',
                'lastname' => 'Laurisch',
                'email' => 'dlaurisch1d@comsenz.com',
                'password' => 'CUx96q',
                'tel' => '+374 945 294 0969',
                'age' => 38,
                'type' => 'normal',
                'remember_token' => NULL,
                'created_at' => '2018-04-22 00:00:00',
                'updated_at' => '2018-05-12 00:00:00',
                'gender' => 'Male',
            ),
            51 => 
            array (
                'firstname' => 'Emelita',
                'lastname' => 'Southon',
                'email' => 'esouthon1e@omniture.com',
                'password' => 'ngeNkNq',
                'tel' => '+86 606 251 5054',
                'age' => 37,
                'type' => 'normal',
                'remember_token' => NULL,
                'created_at' => '2018-03-12 00:00:00',
                'updated_at' => '2018-01-03 00:00:00',
                'gender' => 'Male',
            ),
            52 => 
            array (
                'firstname' => 'Sunny',
                'lastname' => 'Rodmell',
                'email' => 'srodmell1f@nationalgeographic.com',
                'password' => 'Yi1H95M',
                'tel' => '+81 507 745 2814',
                'age' => 38,
                'type' => 'normal',
                'remember_token' => NULL,
                'created_at' => '2018-05-26 00:00:00',
                'updated_at' => '2017-08-23 00:00:00',
                'gender' => 'Female',
            ),
            53 => 
            array (
                'firstname' => 'Kenton',
                'lastname' => 'Castro',
                'email' => 'kcastro1g@about.me',
                'password' => 'F51StrCM',
                'tel' => '+62 946 912 9050',
                'age' => 40,
                'type' => 'manager',
                'remember_token' => NULL,
                'created_at' => '2017-11-28 00:00:00',
                'updated_at' => '2018-03-10 00:00:00',
                'gender' => 'Male',
            ),
            54 => 
            array (
                'firstname' => 'Rianon',
                'lastname' => 'Jagoe',
                'email' => 'rjagoe1h@toplist.cz',
                'password' => 'AMgLdAjN',
                'tel' => '+86 289 550 1687',
                'age' => 38,
                'type' => 'coach',
                'remember_token' => NULL,
                'created_at' => '2018-05-02 00:00:00',
                'updated_at' => '2017-12-09 00:00:00',
                'gender' => 'Female',
            ),
            55 => 
            array (
                'firstname' => 'Jethro',
                'lastname' => 'Epsly',
                'email' => 'jepsly1i@biglobe.ne.jp',
                'password' => 'cgL8TCIz',
                'tel' => '+86 339 864 2128',
                'age' => 21,
                'type' => 'manager',
                'remember_token' => NULL,
                'created_at' => '2018-01-29 00:00:00',
                'updated_at' => '2018-05-09 00:00:00',
                'gender' => 'Male',
            ),
            56 => 
            array (
                'firstname' => 'Siouxie',
                'lastname' => 'Baigent',
                'email' => 'sbaigent1j@nytimes.com',
                'password' => 'HmAEYj',
                'tel' => '+86 105 324 0382',
                'age' => 30,
                'type' => 'manager',
                'remember_token' => NULL,
                'created_at' => '2017-08-16 00:00:00',
                'updated_at' => '2017-10-19 00:00:00',
                'gender' => 'Male',
            ),
            57 => 
            array (
                'firstname' => 'Tersina',
                'lastname' => 'Anmore',
                'email' => 'tanmore1k@chronoengine.com',
                'password' => '7Qn5YrVW3c',
                'tel' => '+48 668 595 8733',
                'age' => 49,
                'type' => 'normal',
                'remember_token' => NULL,
                'created_at' => '2018-06-22 00:00:00',
                'updated_at' => '2017-09-14 00:00:00',
                'gender' => 'Female',
            ),
            58 => 
            array (
                'firstname' => 'Zacharia',
                'lastname' => 'Frederick',
                'email' => 'zfrederick1l@shinystat.com',
                'password' => 'RXUfAGo',
                'tel' => '+86 735 796 3680',
                'age' => 20,
                'type' => 'normal',
                'remember_token' => NULL,
                'created_at' => '2018-04-27 00:00:00',
                'updated_at' => '2018-05-28 00:00:00',
                'gender' => 'Male',
            ),
            59 => 
            array (
                'firstname' => 'Cristi',
                'lastname' => 'Allabush',
                'email' => 'callabush1m@intel.com',
                'password' => 'kHNrcAtX',
                'tel' => '+370 685 911 2994',
                'age' => 20,
                'type' => 'coach',
                'remember_token' => NULL,
                'created_at' => '2018-05-09 00:00:00',
                'updated_at' => '2017-10-31 00:00:00',
                'gender' => 'Female',
            ),
            60 => 
            array (
                'firstname' => 'Vonny',
                'lastname' => 'Beilby',
                'email' => 'vbeilby1n@howstuffworks.com',
                'password' => 'i6qeUiqk',
                'tel' => '+7 638 280 6098',
                'age' => 46,
                'type' => 'coach',
                'remember_token' => NULL,
                'created_at' => '2018-07-01 00:00:00',
                'updated_at' => '2017-10-04 00:00:00',
                'gender' => 'Female',
            ),
            61 => 
            array (
                'firstname' => 'Babbie',
                'lastname' => 'Bonsall',
                'email' => 'bbonsall1o@mediafire.com',
                'password' => 'oVsKBoaQFzYH',
                'tel' => '+55 457 807 4014',
                'age' => 38,
                'type' => 'coach',
                'remember_token' => NULL,
                'created_at' => '2017-12-30 00:00:00',
                'updated_at' => '2017-12-30 00:00:00',
                'gender' => 'Female',
            ),
            62 => 
            array (
                'firstname' => 'Cindy',
                'lastname' => 'Wann',
                'email' => 'cwann1p@epa.gov',
                'password' => 'XPg3vVcc0QsT',
                'tel' => '+967 157 702 9247',
                'age' => 35,
                'type' => 'coach',
                'remember_token' => NULL,
                'created_at' => '2017-07-28 00:00:00',
                'updated_at' => '2018-01-11 00:00:00',
                'gender' => 'Male',
            ),
            63 => 
            array (
                'firstname' => 'Jade',
                'lastname' => 'Shapcote',
                'email' => 'jshapcote1q@cbsnews.com',
                'password' => 'eGomE9FuO9',
                'tel' => '+86 225 594 2501',
                'age' => 25,
                'type' => 'coach',
                'remember_token' => NULL,
                'created_at' => '2017-09-06 00:00:00',
                'updated_at' => '2017-11-07 00:00:00',
                'gender' => 'Male',
            ),
            64 => 
            array (
                'firstname' => 'Sadie',
                'lastname' => 'Pendre',
                'email' => 'spendre1r@marketwatch.com',
                'password' => 'pP47WLL0V',
                'tel' => '+66 105 241 8242',
                'age' => 37,
                'type' => 'coach',
                'remember_token' => NULL,
                'created_at' => '2018-05-25 00:00:00',
                'updated_at' => '2018-01-25 00:00:00',
                'gender' => 'Male',
            ),
            65 => 
            array (
                'firstname' => 'Dina',
                'lastname' => 'Matiewe',
                'email' => 'dmatiewe1s@imageshack.us',
                'password' => 'nAJCrxrC7sQZ',
                'tel' => '+62 630 552 8207',
                'age' => 60,
                'type' => 'manager',
                'remember_token' => NULL,
                'created_at' => '2017-12-18 00:00:00',
                'updated_at' => '2017-08-03 00:00:00',
                'gender' => 'Female',
            ),
            66 => 
            array (
                'firstname' => 'Angel',
                'lastname' => 'Woloschinski',
                'email' => 'awoloschinski1t@weather.com',
                'password' => 'RiD203t',
                'tel' => '+55 453 843 6042',
                'age' => 45,
                'type' => 'normal',
                'remember_token' => NULL,
                'created_at' => '2017-10-25 00:00:00',
                'updated_at' => '2018-04-20 00:00:00',
                'gender' => 'Female',
            ),
            67 => 
            array (
                'firstname' => 'Godfry',
                'lastname' => 'O\'Deegan',
                'email' => 'godeegan1u@ftc.gov',
                'password' => 'PeAKkvggu',
                'tel' => '+46 943 242 2671',
                'age' => 19,
                'type' => 'manager',
                'remember_token' => NULL,
                'created_at' => '2017-08-29 00:00:00',
                'updated_at' => '2017-09-28 00:00:00',
                'gender' => 'Female',
            ),
            68 => 
            array (
                'firstname' => 'Merlina',
                'lastname' => 'Jobbins',
                'email' => 'mjobbins1v@nasa.gov',
                'password' => '9uS49Q5hkV6',
                'tel' => '+51 453 256 6150',
                'age' => 55,
                'type' => 'manager',
                'remember_token' => NULL,
                'created_at' => '2018-04-24 00:00:00',
                'updated_at' => '2017-12-13 00:00:00',
                'gender' => 'Male',
            ),
            69 => 
            array (
                'firstname' => 'Albert',
                'lastname' => 'Ringham',
                'email' => 'aringham1w@over-blog.com',
                'password' => 'QEfdKnFt9z',
                'tel' => '+504 364 804 6805',
                'age' => 37,
                'type' => 'normal',
                'remember_token' => NULL,
                'created_at' => '2018-06-09 00:00:00',
                'updated_at' => '2018-06-04 00:00:00',
                'gender' => 'Male',
            ),
            70 => 
            array (
                'firstname' => 'Rog',
                'lastname' => 'Felix',
                'email' => 'rfelix1x@biblegateway.com',
                'password' => 'hswf6n69skF',
                'tel' => '+48 983 461 0286',
                'age' => 21,
                'type' => 'coach',
                'remember_token' => NULL,
                'created_at' => '2018-03-13 00:00:00',
                'updated_at' => '2017-09-05 00:00:00',
                'gender' => 'Female',
            ),
            71 => 
            array (
                'firstname' => 'Ryun',
                'lastname' => 'Mundford',
                'email' => 'rmundford1y@wisc.edu',
                'password' => 'lUCL8rrw',
                'tel' => '+385 414 733 1915',
                'age' => 39,
                'type' => 'normal',
                'remember_token' => NULL,
                'created_at' => '2017-12-28 00:00:00',
                'updated_at' => '2017-09-20 00:00:00',
                'gender' => 'Male',
            ),
            72 => 
            array (
                'firstname' => 'Glen',
                'lastname' => 'Le Provost',
                'email' => 'gleprovost1z@4shared.com',
                'password' => 'lLOrcBw3',
                'tel' => '+55 695 203 7395',
                'age' => 18,
                'type' => 'coach',
                'remember_token' => NULL,
                'created_at' => '2018-07-01 00:00:00',
                'updated_at' => '2018-04-23 00:00:00',
                'gender' => 'Male',
            ),
            73 => 
            array (
                'firstname' => 'Gay',
                'lastname' => 'Hambly',
                'email' => 'ghambly20@tiny.cc',
                'password' => 'p5ArHk',
                'tel' => '+84 284 399 7970',
                'age' => 32,
                'type' => 'manager',
                'remember_token' => NULL,
                'created_at' => '2018-04-19 00:00:00',
                'updated_at' => '2018-01-02 00:00:00',
                'gender' => 'Male',
            ),
            74 => 
            array (
                'firstname' => 'Corrine',
                'lastname' => 'Axford',
                'email' => 'caxford21@edublogs.org',
                'password' => 'cf9klj5EAG',
                'tel' => '+7 486 362 0400',
                'age' => 46,
                'type' => 'coach',
                'remember_token' => NULL,
                'created_at' => '2018-01-28 00:00:00',
                'updated_at' => '2018-01-02 00:00:00',
                'gender' => 'Male',
            ),
            75 => 
            array (
                'firstname' => 'Shandy',
                'lastname' => 'Dufore',
                'email' => 'sdufore22@nymag.com',
                'password' => 'enI4Lp6IEuZ',
                'tel' => '+86 325 959 4984',
                'age' => 27,
                'type' => 'coach',
                'remember_token' => NULL,
                'created_at' => '2017-12-27 00:00:00',
                'updated_at' => '2018-03-12 00:00:00',
                'gender' => 'Female',
            ),
            76 => 
            array (
                'firstname' => 'Caron',
                'lastname' => 'Gabriely',
                'email' => 'cgabriely23@fc2.com',
                'password' => 'U4qP6P8',
                'tel' => '+86 682 228 7047',
                'age' => 29,
                'type' => 'coach',
                'remember_token' => NULL,
                'created_at' => '2018-04-25 00:00:00',
                'updated_at' => '2018-03-17 00:00:00',
                'gender' => 'Male',
            ),
            77 => 
            array (
                'firstname' => 'Delly',
                'lastname' => 'Harnor',
                'email' => 'dharnor24@scribd.com',
                'password' => 'hg3FwJ',
                'tel' => '+7 602 108 6308',
                'age' => 46,
                'type' => 'normal',
                'remember_token' => NULL,
                'created_at' => '2017-07-24 00:00:00',
                'updated_at' => '2018-02-11 00:00:00',
                'gender' => 'Female',
            ),
            78 => 
            array (
                'firstname' => 'Mickie',
                'lastname' => 'Golbourn',
                'email' => 'mgolbourn25@timesonline.co.uk',
                'password' => 'U4DUmu',
                'tel' => '+34 828 855 1313',
                'age' => 45,
                'type' => 'manager',
                'remember_token' => NULL,
                'created_at' => '2018-05-31 00:00:00',
                'updated_at' => '2018-06-11 00:00:00',
                'gender' => 'Male',
            ),
            79 => 
            array (
                'firstname' => 'Tulley',
                'lastname' => 'Middis',
                'email' => 'tmiddis26@cam.ac.uk',
                'password' => 'HMyKZic2V',
                'tel' => '+66 668 344 5237',
                'age' => 28,
                'type' => 'normal',
                'remember_token' => NULL,
                'created_at' => '2017-12-13 00:00:00',
                'updated_at' => '2017-09-27 00:00:00',
                'gender' => 'Male',
            ),
            80 => 
            array (
                'firstname' => 'Dorry',
                'lastname' => 'Stout',
                'email' => 'dstout27@archive.org',
                'password' => '7a3bJIz11Yr4',
                'tel' => '+33 169 756 1191',
                'age' => 56,
                'type' => 'manager',
                'remember_token' => NULL,
                'created_at' => '2017-07-21 00:00:00',
                'updated_at' => '2018-01-30 00:00:00',
                'gender' => 'Female',
            ),
            81 => 
            array (
                'firstname' => 'Aguste',
                'lastname' => 'Itzak',
                'email' => 'aitzak28@dion.ne.jp',
                'password' => 'fhXLW2yDD',
                'tel' => '+46 266 654 8805',
                'age' => 31,
                'type' => 'coach',
                'remember_token' => NULL,
                'created_at' => '2017-12-09 00:00:00',
                'updated_at' => '2018-01-02 00:00:00',
                'gender' => 'Female',
            ),
            82 => 
            array (
                'firstname' => 'Brewster',
                'lastname' => 'Stoltz',
                'email' => 'bstoltz29@craigslist.org',
                'password' => 'sq34BknUnMTc',
                'tel' => '+62 891 242 6379',
                'age' => 36,
                'type' => 'normal',
                'remember_token' => NULL,
                'created_at' => '2018-02-06 00:00:00',
                'updated_at' => '2018-06-21 00:00:00',
                'gender' => 'Male',
            ),
            83 => 
            array (
                'firstname' => 'Sol',
                'lastname' => 'Cuttle',
                'email' => 'scuttle2a@utexas.edu',
                'password' => '1YHWbfPdk',
                'tel' => '+86 763 297 4492',
                'age' => 19,
                'type' => 'manager',
                'remember_token' => NULL,
                'created_at' => '2017-09-28 00:00:00',
                'updated_at' => '2018-03-17 00:00:00',
                'gender' => 'Female',
            ),
            84 => 
            array (
                'firstname' => 'Elysee',
                'lastname' => 'Townley',
                'email' => 'etownley2b@dell.com',
                'password' => 'PmewYN3PzX',
                'tel' => '+86 475 374 1156',
                'age' => 34,
                'type' => 'coach',
                'remember_token' => NULL,
                'created_at' => '2018-06-19 00:00:00',
                'updated_at' => '2017-10-20 00:00:00',
                'gender' => 'Female',
            ),
            85 => 
            array (
                'firstname' => 'Doralynn',
                'lastname' => 'Habben',
                'email' => 'dhabben2c@virginia.edu',
                'password' => 'DE5yIrOF9I9I',
                'tel' => '+234 812 127 9477',
                'age' => 19,
                'type' => 'manager',
                'remember_token' => NULL,
                'created_at' => '2018-06-30 00:00:00',
                'updated_at' => '2017-09-17 00:00:00',
                'gender' => 'Male',
            ),
            86 => 
            array (
                'firstname' => 'Javier',
                'lastname' => 'Maffetti',
                'email' => 'jmaffetti2d@altervista.org',
                'password' => 'j9RAfwO',
                'tel' => '+48 895 877 5334',
                'age' => 24,
                'type' => 'manager',
                'remember_token' => NULL,
                'created_at' => '2018-05-19 00:00:00',
                'updated_at' => '2018-06-03 00:00:00',
                'gender' => 'Female',
            ),
            87 => 
            array (
                'firstname' => 'Linette',
                'lastname' => 'Birkenhead',
                'email' => 'lbirkenhead2e@marketwatch.com',
                'password' => 'I6KN1sb',
                'tel' => '+63 152 469 2589',
                'age' => 45,
                'type' => 'coach',
                'remember_token' => NULL,
                'created_at' => '2017-11-16 00:00:00',
                'updated_at' => '2017-11-16 00:00:00',
                'gender' => 'Male',
            ),
            88 => 
            array (
                'firstname' => 'Fonz',
                'lastname' => 'Armal',
                'email' => 'farmal2f@mac.com',
                'password' => '3TUjSk0',
                'tel' => '+1 413 209 1520',
                'age' => 49,
                'type' => 'manager',
                'remember_token' => NULL,
                'created_at' => '2017-11-09 00:00:00',
                'updated_at' => '2018-01-15 00:00:00',
                'gender' => 'Female',
            ),
            89 => 
            array (
                'firstname' => 'Zoe',
                'lastname' => 'Heake',
                'email' => 'zheake2g@cafepress.com',
                'password' => '8YDNgaE',
                'tel' => '+420 710 481 5850',
                'age' => 55,
                'type' => 'manager',
                'remember_token' => NULL,
                'created_at' => '2017-08-26 00:00:00',
                'updated_at' => '2017-12-10 00:00:00',
                'gender' => 'Female',
            ),
            90 => 
            array (
                'firstname' => 'Homere',
                'lastname' => 'Loftie',
                'email' => 'hloftie2h@narod.ru',
                'password' => 'twgZLE65',
                'tel' => '+57 298 295 4565',
                'age' => 43,
                'type' => 'manager',
                'remember_token' => NULL,
                'created_at' => '2017-11-29 00:00:00',
                'updated_at' => '2018-05-27 00:00:00',
                'gender' => 'Female',
            ),
            91 => 
            array (
                'firstname' => 'Shelley',
                'lastname' => 'Macartney',
                'email' => 'smacartney2i@redcross.org',
                'password' => 'UqaWUllNSXe',
                'tel' => '+86 315 766 0082',
                'age' => 42,
                'type' => 'coach',
                'remember_token' => NULL,
                'created_at' => '2018-02-18 00:00:00',
                'updated_at' => '2017-09-19 00:00:00',
                'gender' => 'Female',
            ),
            92 => 
            array (
                'firstname' => 'Carlota',
                'lastname' => 'Schnitter',
                'email' => 'cschnitter2j@forbes.com',
                'password' => '2HHwI34cLy',
                'tel' => '+86 398 671 3021',
                'age' => 53,
                'type' => 'manager',
                'remember_token' => NULL,
                'created_at' => '2018-05-29 00:00:00',
                'updated_at' => '2018-02-08 00:00:00',
                'gender' => 'Female',
            ),
            93 => 
            array (
                'firstname' => 'Rebekkah',
                'lastname' => 'McQuilliam',
                'email' => 'rmcquilliam2k@bing.com',
                'password' => 'yGxihFR',
                'tel' => '+269 715 813 8360',
                'age' => 50,
                'type' => 'manager',
                'remember_token' => NULL,
                'created_at' => '2018-03-09 00:00:00',
                'updated_at' => '2017-09-05 00:00:00',
                'gender' => 'Female',
            ),
            94 => 
            array (
                'firstname' => 'Ollie',
                'lastname' => 'Huston',
                'email' => 'ohuston2l@naver.com',
                'password' => 'Xe0HuAv',
                'tel' => '+93 527 903 1757',
                'age' => 21,
                'type' => 'normal',
                'remember_token' => NULL,
                'created_at' => '2018-03-08 00:00:00',
                'updated_at' => '2017-12-12 00:00:00',
                'gender' => 'Male',
            ),
            95 => 
            array (
                'firstname' => 'Clemente',
                'lastname' => 'Ewestace',
                'email' => 'cewestace2m@wired.com',
                'password' => 'tzkTou3c',
                'tel' => '+850 548 934 6140',
                'age' => 37,
                'type' => 'normal',
                'remember_token' => NULL,
                'created_at' => '2018-05-06 00:00:00',
                'updated_at' => '2017-07-14 00:00:00',
                'gender' => 'Female',
            ),
            96 => 
            array (
                'firstname' => 'Kele',
                'lastname' => 'Cotterell',
                'email' => 'kcotterell2n@moonfruit.com',
                'password' => 'rr7aud2UFD6',
                'tel' => '+47 139 320 2091',
                'age' => 48,
                'type' => 'manager',
                'remember_token' => NULL,
                'created_at' => '2017-08-09 00:00:00',
                'updated_at' => '2018-03-30 00:00:00',
                'gender' => 'Male',
            ),
            97 => 
            array (
                'firstname' => 'Berget',
                'lastname' => 'Cunrado',
                'email' => 'bcunrado2o@state.tx.us',
                'password' => '9K276Qo9',
                'tel' => '+86 865 768 3645',
                'age' => 21,
                'type' => 'normal',
                'remember_token' => NULL,
                'created_at' => '2017-07-22 00:00:00',
                'updated_at' => '2017-12-17 00:00:00',
                'gender' => 'Male',
            ),
            98 => 
            array (
                'firstname' => 'Micheil',
                'lastname' => 'Prenty',
                'email' => 'mprenty2p@studiopress.com',
                'password' => 'MuK5Bs4Mx',
                'tel' => '+389 998 197 6563',
                'age' => 53,
                'type' => 'coach',
                'remember_token' => NULL,
                'created_at' => '2018-05-07 00:00:00',
                'updated_at' => '2018-03-05 00:00:00',
                'gender' => 'Female',
            ),
            99 => 
            array (
                'firstname' => 'Bail',
                'lastname' => 'Jadczak',
                'email' => 'bjadczak2q@storify.com',
                'password' => 'nmLHndje',
                'tel' => '+596 597 959 4060',
                'age' => 58,
                'type' => 'normal',
                'remember_token' => NULL,
                'created_at' => '2017-08-15 00:00:00',
                'updated_at' => '2017-12-29 00:00:00',
                'gender' => 'Female',
            ),
            100 => 
            array (
                'firstname' => 'Bea',
                'lastname' => 'Galliver',
                'email' => 'bgalliver2r@google.com',
                'password' => '7Q6jAy',
                'tel' => '+81 403 611 3152',
                'age' => 32,
                'type' => 'normal',
                'remember_token' => NULL,
                'created_at' => '2017-08-13 00:00:00',
                'updated_at' => '2017-10-29 00:00:00',
                'gender' => 'Male',
            ),
            101 => 
            array (
                'firstname' => 'Erick',
                'lastname' => 'NK',
                'email' => 'ericknjiru78@gmail.com',
                'password' => '$2y$10$9OmkfhVf8hoo4oAh5x8SxeJEn4l0vckRYR0yS7kgvYSyuA46r4Mi6',
                'tel' => '0718931359',
                'age' => 23,
                'type' => 'normal',
                'remember_token' => NULL,
                'created_at' => '2018-07-07 12:41:55',
                'updated_at' => '2018-07-07 12:41:55',
                'gender' => 'Male',
            ),
        ));
        
        
    }
}